Models/BaseEntityModel.cs
using System;

namespace lost_woods.Models
{
    public abstract class BaseEntity {}
}

Models/ErrorViewModel.cs
using System;

namespace lost_woods.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TrailModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace lost_woods.Models
{
    public class Trail : BaseEntity
    {
        [Key]
        public long id {get;set;}

        [Required]
        [MinLength(2)]
        [Display(Name = "Trail Name")]
        public string name {get; set;}

        [Required]
        [MinLength(10)]
        [Display(Name = "Description")]

        public string description {get;set;}

        [Required]
        [Display(Name = "Length (miles)")]
        public float length {get;set;}

        [Required]
        [Display(Name = "Elevation Gain (feet)")]
        public float elevation {get;set;}

        [Required]
        [Range(-180,180)]
        [Display(Name = "Longitude")]
        public float longitude {get;set;}

        [Required]
        [Range(-90,90)]
        [Display(Name = "Latitude")]
        public float latitude {get;set;}

    }
}

Controllers/TrailController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using lost_woods.Models;
using lost_woods.Factory;

namespace lost_woods.Controllers
{
    public class TrailController : Controller
    {
        private readonly TrailFactory trailFactory;
 
        public TrailController()
        {
            trailFactory = new TrailFactory();
        }

        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            ViewBag.Trails = trailFactory.FindAll();
            return View();
        }

        [HttpGet]
        [Route("trail/{trail_id}")]
        public IActionResult Show(int trail_id)
        {
            Trail trail = trailFactory.FindByID(trail_id);
            ViewBag.Trail = trail;
            float longitude = ViewBag.Trail.longitude;
            return View("Show", trail);
        }

        [HttpGet]
        [Route("trail/new")]
        public IActionResult AddTrail()
        {
            return View("AddTrail");
        }

        [HttpPost]
        [Route("add")]
        public IActionResult AddNew(Trail trail)
        {
            if(ModelState.IsValid)
            {
                trailFactory.Add(trail);
                return RedirectToAction("Index");
            }

            return View("AddTrail");
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lost_woods</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Lost in the Woods</a>
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Trail/AddTrail.cshtml
@model lost_woods.Models.Trail
<div class="header">
    <h2>Add a New Trail</h2>
    <h4><a href="/">Go Home</a></h4>
</div>


<form asp-controller="Trail" asp-action="AddNew" method="post">
    <table class="table" id="borderless">
    <tr>
        <td><label asp-for="name"></label></td>
        <td><input asp-for="name"/></td>
    </tr>
    <tr>
        <td></td>
        <td class="error"><span asp-validation-for="name"></span></td>
    </tr>
    <tr>
        <td><label asp-for="description"></label></td>
        <td><input asp-for="description"/></td>
    </tr>
    <tr>
        <td></td>
        <td class="error"><span asp-validation-for="description"></span></td>
    </tr>
    <tr>
        <td><label asp-for="length"></label></td>
        <td><input asp-for="length"/></td>
    </tr>
    <tr>
        <td></td>
        <td class="error"><span asp-validation-for="length"></span></td>
    </tr>
    <tr>
        <td><label asp-for="elevation"></label></td>
        <td><input asp-for="elevation"/></td>
    </tr>
    <tr>
        <td></td>
        <td class="error"><span asp-validation-for="elevation"></span></td>
    </tr>
    <tr>
        <td><label asp-for="longitude"></label></td>
        <td><input asp-for="longitude"/></td>
    </tr>
    <tr>
        <td></td>
        <td class="error"><span asp-validation-for="longitude"></span></td>
    </tr>
    <tr>
        <td><label asp-for="latitude"></label></td>
        <td><input asp-for="latitude"/></td>
    </tr>
    <tr>
        <td></td>
        <td class="error"><span asp-validation-for="latitude"></span></td>
    </tr>
    <tr>
        <td></td>
        <td><button type="submit">Create Record</button></td>
    </tr>
</table>     
</form>

Views/Trail/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model lost_woods.Models.Trail

<h1>Lost in the Woods</h1> <h3>List of local hiking trails</h3>

<table>
    <tr>
        <th>Trail Name</th>
        <th>Trail Length</th>
        <th>Elevation Change</th>
    </tr>
    @foreach(var trail in @ViewBag.Trails)
    {
        <tr>
            <td><a href="/trail/@trail.id">@trail.name</a></td>
            <td>@trail.length Miles</td>
            <td>@trail.elevation feet</td>
        </tr>
    }    
</table>

<form action="/trail/new" method="get">
    <input type="submit" value="Add a New Trail">
</form>

Views/Trail/Show.cshtml
@model lost_woods.Models.Trail

<div class="info">
    <h1>@ViewBag.Trail.name</h1>
    <h3>Description</h3>
    <h5>@ViewBag.Trail.description</h5>
    <h3>Trail Length</h3>
    <h5>@ViewBag.Trail.length Miles</h5>
    <h3>Elevation Change</h3>
    <h5>@ViewBag.Trail.elevation feet</h5>
</div>
<div class="location">
    <h3><a href="/">Go Home</a></h3>
    <div class="map-box">
        <div id="map">
            <script>
            var map;
            function initMap() {
                map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: -34.397, lng: 150.644},
                zoom: 8
                });
            }
            </script>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQt3KZ9IAXdhLQv2gTabcAP4fgMNPGpSw&callback=initMap"
            async defer></script>
            </div>
            <h5>Longitude : @ViewBag.Trail.longitude</h5>
            <h5>Latitude : @ViewBag.Trail.latitude</h5>
</div>